networks:
  app_network:
    driver: bridge

services:

  #! NGINX REVERSE PROXY!!
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.local:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

  #! BACKEND!!
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=booklibrary
    restart: unless-stopped

  #! FRONTEND
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    expose:
      - "3000"
    networks:
      - app_network
    environment:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: booklibrary
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: