networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: cloud.Dockerfile
    volumes:
      - /etc/nginx/ssl:/app/ssl:ro
    expose:
      - "8080"
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=booklibrary
      - SSL_CERT_PATH=/app/ssl/books.bchwy.com.crt
      - SSL_KEY_PATH=/app/ssl/books.bchwy.com.key
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: cloud.Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=https://${PUBLIC_IP}/api
    volumes:
      - /etc/nginx/ssl:/app/ssl:ro
    expose:
      - "3000"
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://${PUBLIC_IP}/api
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: booklibrary
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
